const data = [
  {
    audio: "../audio/audio.mp3",
    img: "../img/1.webp",
    artists: "Test Artists1",
    album: "Test Album1",
    duration: "2:20",
  },
  {
    audio: "../audio/audio1.mp3",
    img: "../img/2.webp",
    artists: "Test Artists2",
    album: "Test Album2",
    duration: "3:02",
  },
  {
    audio: "../audio/audio2.mp3",
    img: "../img/3.webp",
    artists: "Test Artists3",
    album: "Test Album3",
    duration: "5:07",
  },
  {
    audio: "../audio/audio3.mp3",
    img: "../img/4.webp",
    artists: "Test Artists4",
    album: "Test Album4",
    duration: "2:14",
  },
  {
    audio: "../audio/audio4.mp3",
    img: "../img/5.jpg",
    artists: "Test Artists5",
    album: "Test Album5",
    duration: "1:44",
  },
  {
    audio: "../audio/audio5.mp3",
    img: "../img/6.jpg",
    artists: "Test Artists6",
    album: "Test Album6",
    duration: "2:44",
  },
  {
    audio: "../audio/audio6.mp3",
    img: "../img/1.webp",
    artists: "Test Artists7",
    album: "Test Album7",
    duration: "3:01",
  },
  {
    audio: "../audio/audio7.mp3",
    img: "../img/2.webp",
    artists: "Test Artists8",
    album: "Test Album8",
    duration: "2:12",
  },
  {
    audio: "../audio/audio8.mp3",
    img: "../img/3.webp",
    artists: "Test Artists9",
    album: "Test Album9",
    duration: "2:12",
  },
  {
    audio: "../audio/audio9.mp3",
    img: "../img/4.webp",
    artists: "Test Artists10",
    album: "Test Album10",
    duration: "2:18",
  },
  {
    audio: "../audio/audio10.mp3",
    img: "../img/1.webp",
    artists: "Test Artists11",
    album: "Test Album11",
    duration: "3:36",
  },
  {
    audio: "../audio/audio11.mp3",
    img: "../img/2.webp",
    artists: "Test Artists12",
    album: "Test Album12",
    duration: "2:01",
  },
];
